### ISSUE TITLE
Functions to create a Period from a single dateTime

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/Expressif#90]
It should be possible to create a function from a single dateTime. The following functions should be read as `dateTime-to-period-...`

- [ ] starting-now : returns a period where the date argument is the end of the period and the beginning is now
- [ ] ending-now : returns a period where the date argument is the beginning of the period and the end is now
- [ ] starting-ago(timestamp) : returns a period where the date argument is the end of the period and the duration of the interval is equal to the timestamp.
- [ ] ending-in(timestamp) : returns a period where the date argument is the beginning of the period and the duration of the interval is equal to the timestamp.
- [ ] covering(timestamp) : returns a period where the date argument is the middle of the period and the duration of the interval is equal to the timestamp.
- [ ] starting-at(dateTime) : returns a period where the date argument is the end of the period and the date provided as parameter of the function is the beginning
- [ ] ending-at(dateTime) : returns a period where the date argument is the beginning of the period and the date provided as parameter of the function is the end
