### ISSUE TITLE
Predicates comparing dateTime and periods

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/Expressif#91]
## Period as argument

- [ ] includes(dateTime)
- [ ] begins-at(dateTime)
- [ ] ends-at(dateTime)

## DateTime as argument

- [ ] included-in(period)
- [ ] begins-at(dateTime)
- [ ] ends-at(dateTime)
